### ISSUE TITLE
Knowledge Base

### ISSUE THREAD

**Issue by Gizmotronn** [acord-robotics/portal#19]
To allow our members to determine how ACoRD works, what they can do and how the network of site works, we'll set up a knowledge base. This will not be a wordpress plugin (in the interest of keeping the site as fast as possible), instead it will be a separate git installation. I'm busy looking at themes now.

Liam

**Comment by Gizmotronn** [comment]
Gitbook looks really nice
https://acordrobotics.getoutline.com/
Bootstrap knowledge base: https://github.com/sunnyg1210/bootstrapKnowledgeBaseTheme
https://www.nuclino.com/solutions/internal-knowledge-base-software?utm_source=aw&utm_content=kb&gclid=CjwKCAiAg9rxBRADEiwAxKDTurxlY6gMHCeoxGP4KZo8-H-Sn6W6uee07yXFvnS-Gq-LJuuTxhpCZRoCxA4QAvD_BwE

**Comment by IrisDroidology** [comment]
This is good, however we need to make it work on > ...basic/account.html w/ iframe
