### ISSUE TITLE
Favicon gone

### ISSUE THREAD

**Issue by Gizmotronn** [acord-robotics/portal#44]
#42, #43

**Comment by IrisDroidology** [comment]
https://github.com/acord-robotics/acord-robotics.github.io/commit/31aef890f7e0ca3d3e09fe2024fdb37861f2715c

Just need to add FB Messenger back...

**Comment by IrisDroidology** [comment]
http://codementor.io/@webong/adding-messenger-customer-chat-to-your-website-jdft3pjue
